export default GameCommandType =
{
	SetRideAppearance 			: 0,
	SetLandHeight 				: 1,
	TogglePause 				: 2,
	PlaceTrack 					: 3,
	RemoveTrack 				: 4,
	LoadOrQuit					: 5,
	CreateRide					: 6,
	DemolishRide				: 7,
	SetRideStatus				: 8,
	SetRideVehicules			: 9,
	SetRideName					: 10,
	SetRideSettings				: 11,
	PlaceRideEntranceOrExit 	: 12,
	RemoveRideEntranceOrExit 	: 13,
	RemoveScenery				: 14,
	PlaceScenery				: 15,
	SetWaterHeight				: 16,
	PlacePath					: 17,
	PlacePathFromTrack			: 18,
	RemovePath					: 19,
	ChangeSurfaceStyle			: 20,
	SetRidePrice				: 21,
	SetGuestName				: 22,
	SetStaffName				: 23,
	RaiseLand					: 24,
	LowerLand					: 25,
	EditLandSmooth				: 26,
	RaiseWater					: 27,
	LowerWater					: 28,
	Count						: 29,
	Test						: 30
	
}